spring:
  datasource:
    username: fengye
    password: YNRN8mAth2SKjkNx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.28.104:3306/mingchao?characterEncoding=utf8
  data:
    redis:
      host: localhost
      port: 6379
      password: fengye
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  rabbitmq:
    host: localhost
    port: 5672
    username: fengye
    password: fengye
    virtual-host: /

server:
  port: 8085


upload:
  url:
    image:
      article: upload/image/article/

my-server:
  address: http://111.229.28.104:8085/


